/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownGroup: typeof import('bootstrap-vue-next')['BDropdownGroup']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    BurgerIcon: typeof import('./src/components/icons/BurgerIcon.vue')['default']
    DoughnutChart: typeof import('./src/components/charts/DoughnutChart.vue')['default']
    HeaderVue: typeof import('./src/components/HeaderVue.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    LoginComponent: typeof import('./src/components/authentication/LoginComponent.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    RegisterComponent: typeof import('./src/components/authentication/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateIcon: typeof import('./src/components/icons/UpdateIcon.vue')['default']
    WorkingWeekChart: typeof import('./src/components/charts/WorkingWeekChart.vue')['default']
  }
}
